CREATE TABLE IF NOT EXISTS recycle_bin_purchases (
  id INT AUTO_INCREMENT PRIMARY KEY,
  original_id INT NOT NULL,
  date DATE NOT NULL,
  invoice_number VARCHAR(100) NOT NULL,
  driver VARCHAR(255) NOT NULL,
  location VARCHAR(255) NOT NULL,
  material_id INT NOT NULL,
  kg DECIMAL(10,2) DEFAULT 0.00,
  price DECIMAL(10,2) NOT NULL,
  payment_type ENUM('نەقد','قەرز') NOT NULL,
  exchange_rate DECIMAL(10,0) DEFAULT 150000,
  company_id INT NOT NULL,
  type ENUM('دینار','دۆلار') NOT NULL,
  paid_usd DECIMAL(10,0) DEFAULT 0,
  paid_iqd DECIMAL(10,0) DEFAULT 0,
  remaining_usd DECIMAL(10,2) DEFAULT 0.00,
  remaining_iqd DECIMAL(10,0) DEFAULT NULL,
  bin_id INT DEFAULT NULL,
  amount_iqd DECIMAL(12,2) DEFAULT 0.00,
  price_per_kg_iqd DECIMAL(10,2) DEFAULT 0.00,
  price_per_kg_usd DECIMAL(10,2) DEFAULT 0.00,
  deleted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
); 